PL/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PL/Controllers/PacienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Razor.Generator;
using System.Web.UI.WebControls;

namespace PL.Controllers
{
    public class PacienteController : Controller
    {
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Result resultPacientes = BL.Paciente.GetAll();
            ML.Paciente paciente = new ML.Paciente();
            if (resultPacientes.Correct)
            {
                paciente.Pacientes = resultPacientes.Objects;
                return View(paciente);
            }
            else
            {
                ViewBag.Message = "No hay pacientes en la lista";
                return View(paciente);
            }
        }

        [HttpGet]
        public ActionResult Form(int? idPaciente)
        {
            ML.Result resultTipos = BL.TipoSangre.GetAll();
            ML.Paciente paciente = new ML.Paciente();
            paciente.TipoSangre = new ML.TipoSangre();
            paciente.TipoSangre.TiposSangre = new List<object>();
            paciente.TipoSangre.TiposSangre = resultTipos.Objects;
            if (idPaciente == null)
            {
                ViewBag.Titulo = "Agregar nuevo empleado";
                ViewBag.Accion = "Agregar";
                return View(paciente);
            }
            else
            {
                ViewBag.Titulo = "Modificar nuevo empleado";
                ViewBag.Accion = "Modificar";
                ML.Result resultPaciente = BL.Paciente.GetById(idPaciente.Value);
                if (resultPaciente.Correct)
                {
                    paciente = ((ML.Paciente)resultPaciente.Object);
                    paciente.TipoSangre.TiposSangre = new List<object>();
                    paciente.TipoSangre.TiposSangre = resultTipos.Objects;
                    return View(paciente);
                }
                else
                {
                    ViewBag.Message = "Paciente no encontrado";
                    return View("Modal");
                }
            }

        }

        [HttpPost]
        public ActionResult Form(ML.Paciente paciente)
        {
            if (paciente.IdPaciente == 0)
            {
                ML.Result result = BL.Paciente.Add(paciente);
                if (result.Correct)
                {
                    ViewBag.Titulo = "¡REGISTRADO!";
                    ViewBag.Message = "Paciente registrado";
                    return View("Modal");
                }
                else
                {
                    ViewBag.Titulo = "¡ERROR!";
                    ViewBag.Message = "No se pudo registrar";
                    return View("Modal");
                }
            }
            else
            {
                ML.Result result = BL.Paciente.Update(paciente);
                if (result.Correct)
                {
                    ViewBag.Titulo = "¡MODIFICADO!";
                    ViewBag.Message = "Paciente modificado";
                    return View("Modal");
                }
                else
                {
                    ViewBag.Titulo = "¡ERROR!";
                    ViewBag.Message = "No se pudo modificar";
                    return View("Modal");
                }
            }
        }

        [HttpGet]
        public ActionResult Delete(int idPaciente)
        {
            ML.Result result = BL.Paciente.Delete(idPaciente);
            if (result.Correct)
            {
                ViewBag.Titulo = "¡ELIMINADO!";
                ViewBag.Message = "Paciente eliminado";
                return View("Modal");
            }
            else
            {
                ViewBag.Titulo = "¡ERROR!";
                ViewBag.Message = "No se pudo eliminar";
                return View("Modal");
            }
        }
    }
}

PL/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

PL/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

PL/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

PL/Views/Paciente/Form.cshtml
@model ML.Paciente
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row text-center">
        <h1>@ViewBag.Titulo</h1>
        <hr />
    </div>
    <br />
    <div class="row">
        <p><b>INSTRUCCIONES</b></p>
        <p>Rellene los campos con la informacion del paciente</p>
    </div>
    <br />
    @using (Html.BeginForm("Form", "Paciente", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="row text-center">
            <div class="col-md-3">
                @Html.LabelFor(model => model.IdPaciente, new { @class = "control-label hidden" })
                <div class="input-group">
                    @Html.TextBoxFor(model => model.IdPaciente, new { @class = "form-control hidden" })
                    @Html.ValidationMessageFor(model => model.IdPaciente)
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-3">
                @Html.LabelFor(model => model.Nombre, new { @class = "control-label" })
                <div class="input-group">
                    @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Nombre)
                </div>
            </div>
            <div class="col-md-3">
                @Html.LabelFor(model => model.ApellidoPaterno, new { @class = "control-label" })
                <div class="input-group">
                    @Html.TextBoxFor(model => model.ApellidoPaterno, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ApellidoPaterno)
                </div>
            </div>
            <div class="col-md-3">
                @Html.LabelFor(model => model.ApellidoMaterno, new { @class = "control-label" })
                <div class="input-group">
                    @Html.TextBoxFor(model => model.ApellidoMaterno, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ApellidoMaterno)
                </div>
            </div>
            <div class="col-md-3">
                @Html.LabelFor(model => model.FechaNacimiento, new { @class = "control-label" })
                <div class="input-group">
                    @Html.TextBoxFor(model => model.FechaNacimiento, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.FechaNacimiento)
                </div>
            </div>
        </div>
        <br />
        <div class="row">

            <div class="col-md-3">
                @Html.LabelFor(model => model.FechaIngreso, new { @class = "control-label" })
                <div class="input-group">
                    @Html.TextBoxFor(model => model.FechaIngreso, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.FechaIngreso)
                </div>
            </div>
            <div class="col-md-3">
                @Html.LabelFor(model => model.Sexo, new { @class = "control-label" })
                <div class="form-group">
                    Masculino
                    @Html.RadioButtonFor(model => model.Sexo, "M")
                    Femenino
                    @Html.RadioButtonFor(model => model.Sexo, "F")
                    @Html.ValidationMessageFor(model => model.Sexo)
                </div>
            </div>
            <div class="col-md-3">
                @Html.LabelFor(model => model.TipoSangre.IdTipoSangre, new { @class = "control-label" })
                <div class="input-group">
                    @Html.DropDownListFor(model => model.TipoSangre.IdTipoSangre, new SelectList(Model.TipoSangre.TiposSangre, "IdTipoSangre", "Nombre"), "Seleccione una opcion...", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TipoSangre.IdTipoSangre)
                </div>
            </div>
            <div class="col-md-3">
                @Html.LabelFor(model => model.Sintomas, new { @class = "control-label" })
                <div class="input-group">
                    @Html.TextAreaFor(model => model.Sintomas, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Sintomas)
                </div>
            </div>
        </div>
        <hr />
        <br />
        <div class="row">
            <div class="col-md-6">
                <button type="submit" class="btn btn-success col-md-12">@ViewBag.Accion</button>
            </div>
            <div class="col-md-6">
                @Html.ActionLink("Regresar", "GetAll", "Paciente", new { @class = "btn btn-danger col-md-12" })
            </div>
        </div>
    }
</div>

PL/Views/Paciente/GetAll.cshtml
@model ML.Paciente
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row text-center">
        <h1>PACIENTES</h1>
        <hr />
    </div>
    <br />
    <div class="row">
        <p><b>INSTRUCCIONES</b></p>
        <p><b>BOTON VERDE:    </b>Envia a un formulario para registrar un paciente</p>
        <p><b>BOTON AMARILLO: </b>Envia a un formulario para modificar un paciente</p>
        <p><b>BOTON ROJO:     </b>Elimina a un paciente</p>
    </div>
    <br />
    <div class="row">
        <div class="col-md-6">
            @Html.ActionLink("Agregar", "Form", "Paciente", new { @class = "btn btn-success col-md-12" })
        </div>
        <div class="col-md-6">
            @Html.ActionLink("Regresar", "Form", "Paciente", new { @class = "btn btn-danger col-md-12" })
        </div>
    </div>
    <hr />
    <br />
    <div class="row">
        @if (Model.Pacientes != null)
        {
            <table class="table table-hover table-responsive">
                <thead>
                    <tr>
                        <th scope="col">EDITAR</th>
                        <th scope="col" class="visually-hidden">ID PACIENTE</th>
                        <th scope="col">NOMBRE</th>
                        <th scope="col">APELLIDO PATERNO</th>
                        <th scope="col">APELLIDO MATERNO</th>
                        <th scope="col">FECHA NACIMIENTO</th>
                        <th scope="col">FECHA INGRESO</th>
                        <th scope="col">SEXO</th>
                        <th scope="col" class="visually-hidden">ID TIPO SANGRE</th>
                        <th scope="col">TIPO SANGRE</th>
                        <th scope="col">SINTOMAS</th>
                        <th scope="col">ELIMINAR</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (ML.Paciente paciente in Model.Pacientes)
                    {
                        <tr>
                            <td><a href="@Url.Action("Form","Paciente", new { IdPaciente = paciente.IdPaciente })" class="btn btn-warning bi bi-pencil-square"></a></td>
                            <td class="visually-hidden">@paciente.IdPaciente</td>
                            <td>@paciente.Nombre</td>
                            <td>@paciente.ApellidoPaterno</td>
                            <td>@paciente.ApellidoMaterno</td>
                            <td>@paciente.FechaNacimiento</td>
                            <td>@paciente.FechaIngreso</td>
                            <td>@paciente.Sexo</td>
                            <td class="visually-hidden">@paciente.TipoSangre.IdTipoSangre</td>
                            <td>@paciente.TipoSangre.Nombre</td>
                            <td>@paciente.Sintomas</td>
                            <td><a href="@Url.Action("Delete","Paciente", new { IdPaciente = paciente.IdPaciente })" class="btn btn-danger bi bi-trash3-fill"></a></td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <div class="alert alert-danger" role="alert">
                @ViewBag.Message
            </div>
        }
    </div>
</div>

PL/Views/Paciente/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="Modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">
                @*@Html.ActionLink("Regresar", "GetAll", "Materia", htmlAttributes: new { @class = "btn btn-danger" })*@
                @Html.ActionLink("Regresar", "GetAll", "Paciente", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#Modal').modal();
</script>

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Pacientes", "GetAll", "Paciente", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>